version: '3.8'

services:
  items-monitor:
    build:
      context: "./distributed auction intelligence system"
    restart: always
    env_file:
      - "./distributed auction intelligence system/.env"
    volumes:
      - "./distributed auction intelligence system/proxies.txt:/app/proxies.txt"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  dashboard:
    build:
      context: ./Dashboard
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./Dashboard/.env.local
    depends_on:
      - scraper
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
