version: '3.8'

services:
  items-monitor:
    build:
      context: "./bot"
    restart: always
    env_file:
      - "./bot/.env"
    volumes:
      - "./bot/proxies.txt:/app/proxies.txt"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  dashboard:
    build:
      context: "./dashboard"
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - "./dashboard/.env.local"
    depends_on:
      - items-monitor
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

